server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 82.157.237.228:18848
        username: nacos
        password: nacos
        enabled: true
  application:
    name: service-verificationcode
